### ISSUE TITLE
Remove Rating Feature

### ISSUE THREAD

**Issue by pratul20** [pratul20/IIITM-Tracker#3]
Remove the rating feature in search activity

**Comment by vikash485** [comment]
Hey @pratul20, I cannot find any rating feature in the search activity. Can you describe the issue properly?

**Comment by esmerexie** [comment]
hey could you assign this to me? I would be happy to fix it

**Comment by esmerexie** [comment]
I have made a PR for you to look at

**Comment by pratul20** [comment]
@esmerexie Actually, we are organizing an event in our institute to promote open source. So, only institute's students are allowed to contribute in this Repository. Sorry, I cannot merge your PR.

**Comment by vvs-personalstash** [comment]
Hello can I work on this issue ,kindly assign it to me
